name: CI

on:
  push:
  pull_request:

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 20
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2.3.0
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter test --coverage
      - uses: codecov/codecov-action@v1.0.7
        if: matrix.os == 'ubuntu-latest'
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: ./coverage/lcov.info
